############################
# Makefile for C programs  #
# Author: zhiyb (Yubo Zhi) #
############################

TARG = Matrix
OBJS = main.o matrix.o rand.o intarray.o

all: $(TARG)

$(TARG): $(OBJS)
